### ISSUE TITLE
Create docker.compose to macos users

### ISSUE THREAD

**Issue by dersonsena** [dersonsena/yii2-skeleton#10]
Create `docker-compose.macos.yml` with content below:

```yml
version: '3'
services:
  app:
    volumes:
      - nfsmount:/var/www/app

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data${PWD}"
```

Update `up` command in `makefile` to:

```bash
##@ Docker
up: ## Start all project containers
	@echo -e "\n~~> Starting up containers for ${PROJECT_NAME}..."
	docker-compose up -d
	@echo -e "~> [OK] Access Application through url: http://localhost:${DOCKER_APP_PORT}"
```

Insert this command in `makefile`:

```bash
up-macos: ## Start all project containers to MacOS Developers
	@echo -e "\n~~> Starting up containers for ${PROJECT_NAME} (MacOS Users)..."
	docker-compose -f docker-compose.yml -f docker-compose.macos.yml up -d
	@echo -e "~> [OK] Acces Application through url: http://localhost:${DOCKER_APP_PORT}"
```
