### ISSUE TITLE
Create a symlink from public to web

### ISSUE THREAD

**Issue by dersonsena** [dersonsena/yii2-skeleton#13]
Create a symboli link from `public` to `web` folder to easier deploy on shared hosts

```bash
$ ln -s ./web public
```

In `docker-compose.yml` file, remove environments variables from app service as show below:

```yml
services:
  app:
    environment:
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_DEBUGGER=xdebug
```
