### ISSUE TITLE
Change the Docker Image

### ISSUE THREAD

**Issue by dersonsena** [dersonsena/yii2-skeleton#9]
Change the docker image to `webdevops`, because it has more resources and is more robust.

Change the `app` service as below:

```
app:
    container_name: ${DOCKER_APP_SERVICE_NAME}
    image: webdevops/php-nginx-dev:7.2
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/web
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MAX_EXECUTION_TIME=86400
      - PHP_DEBUGGER=xdebug
      - XDEBUG_REMOTE_PORT=9000
      - XDEBUG_REMOTE_AUTOSTART=1
      - XDEBUG_REMOTE_CONNECT_BACK=off
      - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
    ports:
      - '${DOCKER_APP_PORT}:80'
    networks:
      - gs-network
    depends_on:
      - mysql
```
